### ISSUE TITLE
[Request] Set-netshare using SDDL rather than permission string

### ISSUE THREAD

**Issue by haydentrail** [CamFlyerCH/FileShareUtils#11]
Hi, 

Love this module.  Am currently using it to change permissions on a bunch of shares but it would be nice if I could pass the sddl string to the function.  I could copy your functions into my own script but I like the idea of the module having full capability :)

If you are interested the reason for the request is I am dealing with SID history values and so have to evaluate the sddl rather than the access object as it misreports the actual account in use.  

Thanks for the great module

**Comment by CamFlyerCH** [comment]
I added the option in the release 1.0.24 to use an SDDL string instead of the text format. With this also wild even inexistent / unresolvable SID can be set in the share permissions. Preferably I would suggest to set fine grained permissions on the folder an not on the share.  But both works.
So fixed with https://github.com/CamFlyerCH/FileShareUtils/releases/tag/1.0.24
Also the version published in the PSGallery is updated.
